// <auto-generated />
using System;
using LeafTrace.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeafTrace.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808171321_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeafTrace.Domain.Entities.BatchTrackTrace", b =>
                {
                    b.Property<int>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraceId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DestroyedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestroyedBy")
                        .HasColumnType("int");

                    b.Property<string>("DestructionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DispatchDate")
                        .HasColumnType("date");

                    b.Property<string>("ExciseChallanRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("bit");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ManufacturingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PackagingDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("QclogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("QcreleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qcstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawMaterialBatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecallInitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecallInitiatedBy")
                        .HasColumnType("int");

                    b.Property<string>("RecallReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReceiptDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("int");

                    b.Property<int?>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("StampId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("TraceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceabilityChain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseInventoryId")
                        .HasColumnType("int");

                    b.HasKey("TraceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("QclogId");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("StampId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseInventoryId");

                    b.ToTable("BatchTrackTraces");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.BillOfMaterialsBom", b =>
                {
                    b.Property<int>("Bomid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bomid"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("Bomstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bomversion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComponentSequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostContributionPct")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal?>("EffectiveQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ScrapPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SubstituteAllowed")
                        .HasColumnType("bit");

                    b.Property<int?>("SubstituteRawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Bomid");

                    b.HasIndex("ProductId");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("SubstituteRawMaterialId");

                    b.ToTable("BillOfMaterialsBoms");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedSalesRepId")
                        .HasColumnType("int");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankIfsccode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreditDays")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CustomerSince")
                        .HasColumnType("date");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastOrderDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LicenseExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseIssuingAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pannumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerritoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ExciseStamp", b =>
                {
                    b.Property<int>("StampId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StampId"));

                    b.Property<DateOnly?>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AppliedDutyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AppliedQty")
                        .HasColumnType("int");

                    b.Property<int?>("AppliedToProductionOrderId")
                        .HasColumnType("int");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CessAmountPerStamp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DamagedQty")
                        .HasColumnType("int");

                    b.Property<decimal>("DutyAmountPerStamp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExciseOfficerRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernmentOrderRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentChallanRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<int>("ReceivedQty")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingQty")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReturnFiledDate")
                        .HasColumnType("date");

                    b.Property<string>("ReturnFiledRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampDenomination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampSeriesFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampSeriesTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StampType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageLocationBinId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalDutyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StampId");

                    b.HasIndex("AppliedToProductionOrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageLocationBinId");

                    b.ToTable("ExciseStamps");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.MachineMaster", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<string>("AmccontractRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapacityUom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DepreciationRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FloorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("InsuranceRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("LineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceVendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NextMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductionCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MachineId");

                    b.ToTable("MachineMasters");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.PickingPackingList", b =>
                {
                    b.Property<int>("PickPackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PickPackId"));

                    b.Property<int?>("AssignedToPickerId")
                        .HasColumnType("int");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<int?>("CartonCount")
                        .HasColumnType("int");

                    b.Property<string>("CartonNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DispatchReadyAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HumidityAtPacking")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PackedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PackingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PackingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PalletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickPackNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickPackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PickedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PickingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PickingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Qcremarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcverificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("QcverifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QcverifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("SealNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShortQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemperatureAtPacking")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalGrossWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNetWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PickPackId");

                    b.HasIndex("BinId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("PickingPackingLists");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartonsPerMasterCarton")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CigaretteDiameterMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CigaretteLengthMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CompensationCessRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<string>("ExciseDutyBasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExciseDutyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FilterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gstrate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HealthWarningRequired")
                        .HasColumnType("bit");

                    b.Property<string>("HealthWarningText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hsncode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExportProduct")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Mrp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NicotineContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacksPerCarton")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegulatoryApprovalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsPerPack")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("ProductionOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionOrderId"));

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ActualLaborHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ActualQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ActualStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bomid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("LaborCostActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LaborCostPlanned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaterialCostActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaterialCostPlanned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OverheadCostActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverheadCostPlanned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PlannedLaborHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlannedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PlannedStartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForDeviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RejectedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCostActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("YieldPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductionOrderId");

                    b.HasIndex("Bomid");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.QualityControlLog", b =>
                {
                    b.Property<int>("Qcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Qcid"));

                    b.Property<bool?>("BarcodeVerified")
                        .HasColumnType("bit");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CigaretteDiameterMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CigaretteLengthMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DefectCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DrawResistancePa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DrawResistanceSpecMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DrawResistanceSpecMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FailedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FailureMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HealthWarningPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InspectionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InspectorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MoistureContentPct")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MoistureSpecMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MoistureSpecMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ncrnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NicotineLevelMg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NicotineSpecMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NicotineSpecMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OverallResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PackWeightGm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PassedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreventiveAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintingQualityResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("int");

                    b.Property<string>("QcreferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReleasedBy")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SampleSize")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SamplingStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TarLevelMg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarSpecMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarSpecMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TensileStrength")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestReportAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("VentilationPct")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Qcid");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("QualityControlLogs");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.RawMaterial", b =>
                {
                    b.Property<int>("RawMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RawMaterialId"));

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hsncode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsControlledSubstance")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastReceivedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LastReceivedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrimarySupplierId")
                        .HasColumnType("int");

                    b.Property<string>("QualityStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReorderPoint")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RawMaterialId");

                    b.HasIndex("PrimarySupplierId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("BackOrderQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("CessAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cgstamount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ConfirmedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ConfirmedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EwayBillNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExciseDutyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gstrate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Igstamount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInterstate")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ponumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("RequestedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("RoundOff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesRepId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Sgstamount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShippedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SalesOrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ShipmentLog", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<DateTime?>("ActualDeliveryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DispatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispatchLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EwayBillNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedDeliveryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FreightCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lrnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PickPackId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransporterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipmentId");

                    b.HasIndex("PickPackId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("ShipmentLogs");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankIfsccode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlacklistReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreditDays")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LicenseExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pannumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("QualityRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.WarehouseBin", b =>
                {
                    b.Property<int>("BinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinId"));

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentVolumeUsedCbm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentWeightUsedKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxTemperatureC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxVolumeCapacityCbm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxWeightCapacityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinTemperatureC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperatureZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BinId");

                    b.ToTable("WarehouseBins");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.WarehouseInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<decimal?>("AvailableQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DamagedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Grnreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LastCycleCountDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LastCycleCountQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QcreleaseRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuarantineQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservedQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VarianceQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InventoryId");

                    b.HasIndex("BinId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("WarehouseInventories");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.BatchTrackTrace", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.Customer", "Customer")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.QualityControlLog", "Qclog")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("QclogId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", "RawMaterial")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.ShipmentLog", "Shipment")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.ExciseStamp", "Stamp")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("StampId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.Supplier", "Supplier")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.WarehouseInventory", "WarehouseInventory")
                        .WithMany("BatchTrackTraces")
                        .HasForeignKey("WarehouseInventoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Qclog");

                    b.Navigation("RawMaterial");

                    b.Navigation("SalesOrder");

                    b.Navigation("Shipment");

                    b.Navigation("Stamp");

                    b.Navigation("Supplier");

                    b.Navigation("WarehouseInventory");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.BillOfMaterialsBom", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("BillOfMaterialsBoms")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", "RawMaterial")
                        .WithMany("BillOfMaterialsBomRawMaterials")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", "SubstituteRawMaterial")
                        .WithMany("BillOfMaterialsBomSubstituteRawMaterials")
                        .HasForeignKey("SubstituteRawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("RawMaterial");

                    b.Navigation("SubstituteRawMaterial");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ExciseStamp", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.ProductionOrder", "AppliedToProductionOrder")
                        .WithMany("ExciseStamps")
                        .HasForeignKey("AppliedToProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("ExciseStamps")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.WarehouseBin", "StorageLocationBin")
                        .WithMany("ExciseStamps")
                        .HasForeignKey("StorageLocationBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppliedToProductionOrder");

                    b.Navigation("Product");

                    b.Navigation("StorageLocationBin");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.PickingPackingList", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.WarehouseBin", "Bin")
                        .WithMany("PickingPackingLists")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("PickingPackingLists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("PickingPackingLists")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.BillOfMaterialsBom", "Bom")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("Bomid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.MachineMaster", "Machine")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", null)
                        .WithMany("ProductionOrders")
                        .HasForeignKey("RawMaterialId");

                    b.Navigation("Bom");

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.QualityControlLog", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("QualityControlLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("QualityControlLogs")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", "RawMaterial")
                        .WithMany("QualityControlLogs")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.RawMaterial", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.Supplier", "PrimarySupplier")
                        .WithMany("RawMaterials")
                        .HasForeignKey("PrimarySupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimarySupplier");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ShipmentLog", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.PickingPackingList", "PickPack")
                        .WithMany("ShipmentLogs")
                        .HasForeignKey("PickPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("ShipmentLogs")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickPack");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.WarehouseInventory", b =>
                {
                    b.HasOne("LeafTrace.Domain.Entities.WarehouseBin", "Bin")
                        .WithMany("WarehouseInventories")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeafTrace.Domain.Entities.Product", "Product")
                        .WithMany("WarehouseInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeafTrace.Domain.Entities.RawMaterial", "RawMaterial")
                        .WithMany("WarehouseInventories")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bin");

                    b.Navigation("Product");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.BillOfMaterialsBom", b =>
                {
                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Customer", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ExciseStamp", b =>
                {
                    b.Navigation("BatchTrackTraces");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.MachineMaster", b =>
                {
                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.PickingPackingList", b =>
                {
                    b.Navigation("ShipmentLogs");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Product", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("BillOfMaterialsBoms");

                    b.Navigation("ExciseStamps");

                    b.Navigation("PickingPackingLists");

                    b.Navigation("ProductionOrders");

                    b.Navigation("QualityControlLogs");

                    b.Navigation("SalesOrders");

                    b.Navigation("WarehouseInventories");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("ExciseStamps");

                    b.Navigation("QualityControlLogs");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.QualityControlLog", b =>
                {
                    b.Navigation("BatchTrackTraces");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.RawMaterial", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("BillOfMaterialsBomRawMaterials");

                    b.Navigation("BillOfMaterialsBomSubstituteRawMaterials");

                    b.Navigation("ProductionOrders");

                    b.Navigation("QualityControlLogs");

                    b.Navigation("WarehouseInventories");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("PickingPackingLists");

                    b.Navigation("ShipmentLogs");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.ShipmentLog", b =>
                {
                    b.Navigation("BatchTrackTraces");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("BatchTrackTraces");

                    b.Navigation("RawMaterials");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.WarehouseBin", b =>
                {
                    b.Navigation("ExciseStamps");

                    b.Navigation("PickingPackingLists");

                    b.Navigation("WarehouseInventories");
                });

            modelBuilder.Entity("LeafTrace.Domain.Entities.WarehouseInventory", b =>
                {
                    b.Navigation("BatchTrackTraces");
                });
#pragma warning restore 612, 618
        }
    }
}
